# Generated by Django 4.1.4 on 2022-12-25 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='gues_can_pause',
            new_name='guest_can_pause',
        ),
    ]
